services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql/
    ports:
      - "3306:3306"
volumes:
  db_data: